baseurl = "/"
languageCode = "en-us"
title = "Homepage"
publishDir = "../dist"
assetDir = "../src"

[params]
  org = "Evaluation Center"
  logoUrl =  "/img/logos/EC_logo.png"
  title= "Evaluation Center"
  subtitle= "at Northwestern University"
  twitter= "https://twitter.com/editatnu?lang=en"
