backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Featured Projects", name: "featured_projects", widget: "relation", collection: "projects", searchFields: ["heading"], valueField: "heading"}
          - {label: "Values Summary", name: "values_summary", widget: "relation", collection: "values", searchFields: ["heading"], valueField: "heading"}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
          - label: Upcoming Events
            name: events
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Date
                name: date
                widget: date
                default: ""
              - label: Description
                name: description
                widget: text
              - label: Link
                name: event_link
                widget: string
      - file: "site/content/projects/_index.md"
        label: "projects Page"
        name: "projects"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/about/values.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/resources/faq.md"
        label: "FAQ"
        name: "faq"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Questions
            name: questions
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: text}
              - {label: File, name: file, widget: file, default: "/files/"}

      - file: "site/content/resources/publications.md"
        label: "Publications"
        name: "publications"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Publications
            name: publications
            widget: list
            fields:
              - {label: File, name: fileURL, widget: file}
              - {label: Heading, name: heading, widget: string}
              - {label: Authors, name: authors, widget: string}
              - {label: Date, name: date, widget: date}
              - {label: Description, name: description, widget: text}
  - name: "people" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "People" # Used in the UI, ie.: "New Post"
    files:
      - file: "site/content/people/_index.md" # The path to the file where the documents are stored
        label: "Team Info"
        name: "team"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - label: People
            name: people
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Role1, name: role1, widget: text}
              - {label: Role2, name: role2, widget: text}
              - {label: Text, name: text, widget: text}

  - name: "videos" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Videos" # Used in the UI, ie.: "New Post"
    files:
      - file: "site/content/videos/_index.md" # The path to the folder where the documents are stored
        label: "Video List"
        name: "video_list"
        fields:
          - label: Youtube IDs
            name: youtube
            widget: list
            fields:
              - {label: ID, name: id, widget: string}
              # - {label: Description, name: text, widget: text}
